import './lib/assets/bootstrap-datepicker.js';
import './lib/assets/bootstrap-datepicker.el.min.js';
import './lib/assets/bootstrap-datepicker3.css';
import './views/schedule.html';
import './views/schedule.js';
import './views/booking.html';
import './views/booking.js';
import './views/bookingDialog.html';
import './views/bookingDialog.js';
import './views/booking.css';
import './views/result.html';
import './views/result.js';
import './views/cancel.html';
import './views/cancel.js';
// Billing related code - left for future reference
// import './views/billing.html';
// import './views/billing.js';
import './lib/scheduler.css';
import './lib/scheduler.js';
import './lib/fullcalendar.html';
import './lib/fullcalendar.js';
import './lib/fullCalendar.css';
